### 1. Добавить первую машину (BMW X5)
POST http://localhost:8080/api/cars
Content-Type: application/json

{
  "brand": "BMW",
  "model": "X5",
  "pricePerDay": 150.00
}

### 2. Добавить вторую машину (Tesla Model S)
POST http://localhost:8080/api/cars
Content-Type: application/json

{
  "brand": "Tesla",
  "model": "Model S",
  "pricePerDay": 200.00
}

### 3. Посмотреть все машины
GET http://localhost:8080/api/cars


### 4. УСПЕШНОЕ бронирование
POST http://localhost:8080/api/bookings?userId=1&carId=2
Content-Type: application/json

### 5. Проверка статуса машины
GET http://localhost:8080/api/cars

### 6. НЕУДАЧНОЕ бронирование (Тест защиты)
POST http://localhost:8080/api/bookings?userId=1&carId=1
Content-Type: application/json